
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipes4u_development
  host: localhost

test:
  <<: *default
  database: Recipes4u_test

production:
  <<: *default
  database: Recipes4u_production
  username: Recipes4u
  password: <%= ENV['RECIPES4U_DATABASE_PASSWORD'] %>
